### ISSUE TITLE
Criticism

### ISSUE THREAD

**Issue by thehowl** [azbshiri/gigsib#2]
Take this with a grain of salt, and keep in mind this is only my personal opinion.

----------------------

```go
import "foo/bar/baz"

var baz baz.Baz
```

Why would you use a global variable? You're most likely going to use a local variable inside a function, and not a global var, in most cases. And when you use a local variable, the wisdom in the go community is to keep the names short. And, if we want to use the constructor, then only one repetition would be needed:

```go
import "foo/bar/baz"

func myFunc() {
  b := baz.New()
}
```

----------------------

```go
package baz

type Baz struct{}

func NewBaz() Baz {
        // do something
}
```

Yes, this is bad - especially because it's best to use just `func New() Baz`! When I have a function simply called `New()`, I generally assume that what is being created is indicated by the package name - namely, a `Baz`.

----------------------

```go
import Baz "foo/bar/baz"

var baz Baz.Type
```

Using this example, you are still writing `baz` four times (with two different capitalisations) - no improvement from the first example, which would be the """""idiomatic""""" way to do it. The quotes are there because, here again, you're using a global variable - and most variables I've declared were certainly not globals.

-------------------

Finally, the last line you wrote in the document:

>Do you see a big difference between ruby and golang? (expect ! and naming convention and entrypoint)

I don't - and that's a problem! Go is not Ruby, and Ruby is not Go. I am guessing you are a beginner to Go - and trying to bring over concepts and structures from Ruby, and that is understandable. And I'm not going to stop you if you want to use this in your Go packages - I'm just some guy on the internet with opinions. But I still think it's better to think about problems _for_ Go _in_ Go, not in Ruby :)

-------------------------------------------

Finally, here's how I would do it.

`shop/models/basket.go`

```go
package models

type Basket struct {
	Items []BasketItem
}

func (b *Basket) Total() (t int) {
	for _, i := range b.Items {
		t += i.Price
	}
	return
}

func (b *Basket) AddItem(i BasketItem) {
	b.Items = append(b.Items, i)
}

type BasketItem struct {
	Name  string
	Price int
}
```

`shop/main.go`

```go
package main

import (
	"fmt"
	"shop/models"
)

func main() {
	b := &models.Basket{}
	b.AddItem(models.BasketItem{Name: "Nikelab Shoe", Price: 1337})
	b.AddItem(models.BasketItem{Name: "Triple Black Shoe", Price: 420})
	fmt.Println(b.Total())
}
```

**Comment by al3rez** [comment]
Thanks for your attention. I'm not new to Golang I think, I've used it since 1.1 and I've always liked its simplicity but missing static methods and other features bothered me. Golang concepts are not new and even not standard yet (many would agree) so there's room for improvement in style, etc. I agree with you about global state (I hate modifying states, even when it's necessary) and I could have write a better example.

**Comment by al3rez** [comment]
I'd create slide to explain why this is better and I'd be happy to hear you idea.

**Comment by thehowl** [comment]
I'd be honoured. Thanks for hearing me out!
